### ISSUE TITLE
What is this meme

### ISSUE THREAD

**Issue by BuddyBoi** [KakashiiiSan/Spoofer-Fortnite-Apex-FiveM-Rust-EFT-UD#1]
There is just so many things wrong with this. You hardcode if statements to check individual modules and processes instead of iterating some sort of list of strings. That's just the few few seconds of looking, there's so many things wrong with this.

I honestly don't understand why people would make drivers of all things without understanding programming. You're going to fry somebody's computer.

Not to mention the meme bsod function.
Was this actually sold for money?

**Comment by KakashiiiSan** [comment]
it's an old spoofer i have post here because a friend leak it, it's probably badly but it can help a lot of people

**Comment by israelcavalcante54** [comment]
I'm getting "google assistant" error, any solution?
